Failure # 1 (occurred at 2022-02-04_02-33-03)
Traceback (most recent call last):
  File "/home/huanting/SuperSonic/third_party/ray/tune/trial_runner.py", line 468, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/huanting/SuperSonic/third_party/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/huanting/SuperSonic/third_party/ray/worker.py", line 1474, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(InvalidArgumentError): [36mray::MARWIL.train()[39m (pid=116543, ip=192.168.188.130)
  File "/home/huanting/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/huanting/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Received a label value of 9 which is outside the valid range of [0, 9).  Label values: 9
	 [[{{node default_policy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]

During handling of the above exception, another exception occurred:

[36mray::MARWIL.train()[39m (pid=116543, ip=192.168.188.130)
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer.py", line 500, in train
    raise e
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer.py", line 486, in train
    result = Trainable.train(self)
  File "/home/huanting/SuperSonic/third_party/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer_template.py", line 132, in _train
    return self._train_exec_impl()
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer_template.py", line 170, in _train_exec_impl
    res = next(self.train_exec_impl)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 731, in __next__
    return next(self.built_iterator)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 1047, in build_union
    item = next(it)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 731, in __next__
    return next(self.built_iterator)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/rllib/execution/rollout_ops.py", line 70, in sampler
    yield workers.local_worker().sample()
  File "/home/huanting/SuperSonic/third_party/ray/rllib/evaluation/rollout_worker.py", line 528, in sample
    batches = [self.input_reader.next()]
  File "/home/huanting/SuperSonic/third_party/ray/rllib/evaluation/sampler.py", line 59, in next
    batches = [self.get_data()]
  File "/home/huanting/SuperSonic/third_party/ray/rllib/evaluation/sampler.py", line 164, in get_data
    item = next(self.rollout_provider)
  File "/home/huanting/SuperSonic/third_party/ray/rllib/evaluation/sampler.py", line 496, in _env_runner
    eval_results = _do_policy_eval(
  File "/home/huanting/SuperSonic/third_party/ray/rllib/evaluation/sampler.py", line 830, in _do_policy_eval
    eval_results[pid] = builder.get(v)
  File "/home/huanting/SuperSonic/third_party/ray/rllib/utils/tf_run_builder.py", line 48, in get
    raise e
  File "/home/huanting/SuperSonic/third_party/ray/rllib/utils/tf_run_builder.py", line 42, in get
    self._executed = run_timeline(
  File "/home/huanting/SuperSonic/third_party/ray/rllib/utils/tf_run_builder.py", line 89, in run_timeline
    fetches = sess.run(ops, feed_dict=feed_dict)
  File "/home/huanting/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/huanting/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/huanting/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/huanting/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Received a label value of 9 which is outside the valid range of [0, 9).  Label values: 9
	 [[node default_policy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits (defined at /SuperSonic/third_party/ray/rllib/models/tf/tf_action_dist.py:63) ]]

Errors may have originated from an input operation.
Input Source operations connected to node default_policy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits:
 default_policy/truediv (defined at /SuperSonic/third_party/ray/rllib/models/tf/tf_action_dist.py:55)	
 default_policy/Cast (defined at /SuperSonic/third_party/ray/rllib/models/tf/tf_action_dist.py:64)

Original stack trace for 'default_policy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits':
  File "/SuperSonic/third_party/ray/workers/default_worker.py", line 123, in <module>
    ray.worker.global_worker.main_loop()
  File "/SuperSonic/third_party/ray/rllib/agents/trainer_template.py", line 90, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/SuperSonic/third_party/ray/rllib/agents/trainer.py", line 450, in __init__
    super().__init__(config, logger_creator)
  File "/SuperSonic/third_party/ray/tune/trainable.py", line 175, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/SuperSonic/third_party/ray/rllib/agents/trainer.py", line 623, in _setup
    self._init(self.config, self.env_creator)
  File "/SuperSonic/third_party/ray/rllib/agents/trainer_template.py", line 113, in _init
    self.workers = self._make_workers(env_creator, self._policy,
  File "/SuperSonic/third_party/ray/rllib/agents/trainer.py", line 691, in _make_workers
    return WorkerSet(
  File "/SuperSonic/third_party/ray/rllib/evaluation/worker_set.py", line 58, in __init__
    self._local_worker = self._make_worker(
  File "/SuperSonic/third_party/ray/rllib/evaluation/worker_set.py", line 245, in _make_worker
    worker = cls(
  File "/SuperSonic/third_party/ray/rllib/evaluation/rollout_worker.py", line 379, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/SuperSonic/third_party/ray/rllib/evaluation/rollout_worker.py", line 937, in _build_policy_map
    policy_map[name] = cls(obs_space, act_space, merged_conf)
  File "/SuperSonic/third_party/ray/rllib/policy/tf_policy_template.py", line 128, in __init__
    DynamicTFPolicy.__init__(
  File "/SuperSonic/third_party/ray/rllib/policy/dynamic_tf_policy.py", line 215, in __init__
    action_dist = dist_class(dist_inputs, self.model)
  File "/SuperSonic/third_party/ray/rllib/models/tf/tf_action_dist.py", line 55, in __init__
    super().__init__(inputs / temperature, model)
  File "/SuperSonic/third_party/ray/rllib/models/tf/tf_action_dist.py", line 25, in __init__
    self.sampled_action_logp_op = self.logp(self.sample_op)
  File "/SuperSonic/third_party/ray/rllib/models/tf/tf_action_dist.py", line 63, in logp
    return -tf.nn.sparse_softmax_cross_entropy_with_logits(
  File "/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 4139, in sparse_softmax_cross_entropy_with_logits
    cost, _ = gen_nn_ops.sparse_softmax_cross_entropy_with_logits(
  File "/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 11259, in sparse_softmax_cross_entropy_with_logits
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "/anaconda3/envs/compiler_gym/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

